-- =====================================================================
-- V10 - Notificacoes in-app (RF-103) e log de auditoria (RF-095).
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE notificacao (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT NOT NULL,
    titulo      VARCHAR(140) NOT NULL,
    mensagem    VARCHAR(2000) NOT NULL,
    lida        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notificacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE TABLE auditoria (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT,
    usuario_email VARCHAR(180),
    metodo        VARCHAR(10) NOT NULL,
    caminho       VARCHAR(300) NOT NULL,
    status        INTEGER NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notificacao_usuario ON notificacao (usuario_id, lida);
CREATE INDEX idx_auditoria_usuario   ON auditoria (usuario_id);
CREATE INDEX idx_auditoria_data      ON auditoria (created_at);
