-- =====================================================================
-- V1 - Esquema inicial de autenticacao (RF-096 a RF-101)
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE papel (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(30)  NOT NULL UNIQUE,
    descricao   VARCHAR(120)
);

CREATE TABLE usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(120) NOT NULL,
    email             VARCHAR(180) NOT NULL UNIQUE,
    senha_hash        VARCHAR(100) NOT NULL,
    ativo             BOOLEAN      NOT NULL DEFAULT TRUE,
    tentativas_login  INTEGER      NOT NULL DEFAULT 0,
    bloqueado_ate     TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE usuario_papel (
    usuario_id  BIGINT NOT NULL,
    papel_id    BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, papel_id),
    CONSTRAINT fk_up_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_up_papel   FOREIGN KEY (papel_id)   REFERENCES papel (id)   ON DELETE CASCADE
);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(200) NOT NULL UNIQUE,
    usuario_id  BIGINT NOT NULL,
    expira_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    revogado    BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rt_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE TABLE password_reset_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(200) NOT NULL UNIQUE,
    usuario_id  BIGINT NOT NULL,
    expira_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    usado       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_prt_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_usuario ON refresh_token (usuario_id);
CREATE INDEX idx_prt_usuario           ON password_reset_token (usuario_id);
