-- =====================================================================
-- V3 - Nucleo da Academia (RF-041 a RF-055)
-- Modalidade, Plano, Professor, Turma, Aluno, Matricula, Lista de espera.
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE modalidade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(80)  NOT NULL UNIQUE,
    descricao   VARCHAR(500),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE plano (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(80)   NOT NULL,
    descricao         VARCHAR(500),
    valor             NUMERIC(10,2) NOT NULL,
    periodicidade     VARCHAR(20)   NOT NULL,
    aulas_por_semana  INTEGER       NOT NULL DEFAULT 0,
    ativo             BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE plano_modalidade (
    plano_id      BIGINT NOT NULL,
    modalidade_id BIGINT NOT NULL,
    PRIMARY KEY (plano_id, modalidade_id),
    CONSTRAINT fk_pm_plano      FOREIGN KEY (plano_id)      REFERENCES plano (id)      ON DELETE CASCADE,
    CONSTRAINT fk_pm_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade (id) ON DELETE CASCADE
);

CREATE TABLE professor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    email       VARCHAR(180) NOT NULL UNIQUE,
    telefone    VARCHAR(30),
    faixa       VARCHAR(40),
    bio         VARCHAR(1000),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    usuario_id  BIGINT UNIQUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_professor_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

CREATE TABLE aluno (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(120) NOT NULL,
    email               VARCHAR(180) NOT NULL UNIQUE,
    telefone            VARCHAR(30),
    data_nascimento     DATE,
    cpf                 VARCHAR(14),
    contato_emergencia  VARCHAR(120),
    observacoes_saude   VARCHAR(1000),
    faixa_atual         VARCHAR(40),
    ativo               BOOLEAN      NOT NULL DEFAULT TRUE,
    usuario_id          BIGINT UNIQUE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_aluno_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

CREATE TABLE turma (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120) NOT NULL,
    modalidade_id BIGINT NOT NULL,
    professor_id  BIGINT,
    dia_semana    VARCHAR(15) NOT NULL,
    hora_inicio   TIME NOT NULL,
    hora_fim      TIME NOT NULL,
    capacidade    INTEGER NOT NULL DEFAULT 0,
    nivel         VARCHAR(20) NOT NULL,
    ativo         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_turma_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade (id),
    CONSTRAINT fk_turma_professor  FOREIGN KEY (professor_id)  REFERENCES professor (id) ON DELETE SET NULL
);

CREATE TABLE matricula (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id    BIGINT NOT NULL,
    plano_id    BIGINT NOT NULL,
    status      VARCHAR(20) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim    DATE,
    observacao  VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id),
    CONSTRAINT fk_matricula_plano FOREIGN KEY (plano_id) REFERENCES plano (id)
);

CREATE TABLE matricula_turma (
    matricula_id BIGINT NOT NULL,
    turma_id     BIGINT NOT NULL,
    PRIMARY KEY (matricula_id, turma_id),
    CONSTRAINT fk_mt_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id) ON DELETE CASCADE,
    CONSTRAINT fk_mt_turma     FOREIGN KEY (turma_id)     REFERENCES turma (id)     ON DELETE CASCADE
);

CREATE TABLE lista_espera (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma_id    BIGINT NOT NULL,
    aluno_id    BIGINT NOT NULL,
    posicao     INTEGER NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_le_turma FOREIGN KEY (turma_id) REFERENCES turma (id) ON DELETE CASCADE,
    CONSTRAINT fk_le_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id) ON DELETE CASCADE,
    CONSTRAINT uq_le_turma_aluno UNIQUE (turma_id, aluno_id)
);

CREATE INDEX idx_turma_modalidade   ON turma (modalidade_id);
CREATE INDEX idx_turma_professor    ON turma (professor_id);
CREATE INDEX idx_matricula_aluno    ON matricula (aluno_id);
CREATE INDEX idx_matricula_status   ON matricula (status);
CREATE INDEX idx_matricula_turma_t  ON matricula_turma (turma_id);
