-- =====================================================================
-- V5 - Frequencia (check-in) e Graduacao (RF-056 a RF-062, RF-068 a RF-073)
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE check_in (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id    BIGINT NOT NULL,
    turma_id    BIGINT NOT NULL,
    data        DATE   NOT NULL,
    data_hora   TIMESTAMP WITH TIME ZONE NOT NULL,
    origem      VARCHAR(15) NOT NULL,
    CONSTRAINT fk_checkin_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkin_turma FOREIGN KEY (turma_id) REFERENCES turma (id) ON DELETE CASCADE,
    CONSTRAINT uq_checkin_aluno_turma_dia UNIQUE (aluno_id, turma_id, data)
);

CREATE INDEX idx_checkin_aluno ON check_in (aluno_id);
CREATE INDEX idx_checkin_data  ON check_in (data);

-- Tabela de dominio configuravel de faixas (RF-068): adulto e infantil.
CREATE TABLE faixa (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(40) NOT NULL,
    categoria   VARCHAR(15) NOT NULL,
    ordem       INTEGER NOT NULL,
    graus_max   INTEGER NOT NULL DEFAULT 4,
    ativo       BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_faixa_nome_categoria UNIQUE (nome, categoria)
);

-- Historico append-only de graduacoes (RF-070).
CREATE TABLE graduacao (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id      BIGINT NOT NULL,
    faixa_id      BIGINT NOT NULL,
    graus         INTEGER NOT NULL DEFAULT 0,
    data          DATE NOT NULL,
    professor_id  BIGINT,
    observacao    VARCHAR(500),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_grad_aluno     FOREIGN KEY (aluno_id)     REFERENCES aluno (id)     ON DELETE CASCADE,
    CONSTRAINT fk_grad_faixa     FOREIGN KEY (faixa_id)     REFERENCES faixa (id),
    CONSTRAINT fk_grad_professor FOREIGN KEY (professor_id) REFERENCES professor (id) ON DELETE SET NULL
);

CREATE INDEX idx_grad_aluno ON graduacao (aluno_id);
