-- =====================================================================
-- V7 - Financeiro (RF-074 a RF-082): mensalidades e pagamentos.
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE mensalidade (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id    BIGINT NOT NULL,
    ano             INTEGER NOT NULL,
    mes             INTEGER NOT NULL,
    valor           NUMERIC(10,2) NOT NULL,
    multa           NUMERIC(10,2) NOT NULL DEFAULT 0,
    juros           NUMERIC(10,2) NOT NULL DEFAULT 0,
    valor_pago      NUMERIC(10,2),
    data_vencimento DATE NOT NULL,
    data_pagamento  DATE,
    status          VARCHAR(15) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_mensalidade_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id) ON DELETE CASCADE,
    CONSTRAINT uq_mensalidade_competencia UNIQUE (matricula_id, ano, mes)
);

CREATE TABLE pagamento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensalidade_id  BIGINT NOT NULL,
    valor           NUMERIC(10,2) NOT NULL,
    metodo          VARCHAR(15) NOT NULL,
    status          VARCHAR(15) NOT NULL,
    gateway_id      VARCHAR(80),
    data_hora       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pagamento_mensalidade FOREIGN KEY (mensalidade_id) REFERENCES mensalidade (id) ON DELETE CASCADE
);

CREATE INDEX idx_mensalidade_status ON mensalidade (status);
CREATE INDEX idx_mensalidade_venc   ON mensalidade (data_vencimento);
CREATE INDEX idx_pagamento_mens     ON pagamento (mensalidade_id);
