-- =====================================================================
-- V8 - E-commerce (RF-011 a RF-040): catalogo, carrinho, pedidos, cupons.
-- Compativel com PostgreSQL e H2 (modo PostgreSQL).
-- =====================================================================

CREATE TABLE categoria (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR(80) NOT NULL UNIQUE,
    ativo  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE produto (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(140) NOT NULL,
    descricao    VARCHAR(2000),
    categoria_id BIGINT NOT NULL,
    preco        NUMERIC(10,2) NOT NULL,
    ativo        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE produto_imagem (
    produto_id BIGINT NOT NULL,
    url        VARCHAR(500) NOT NULL,
    CONSTRAINT fk_produto_imagem FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE CASCADE
);

CREATE TABLE variacao_produto (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id      BIGINT NOT NULL,
    sku             VARCHAR(60) NOT NULL UNIQUE,
    tamanho         VARCHAR(20),
    cor             VARCHAR(30),
    preco_adicional NUMERIC(10,2) NOT NULL DEFAULT 0,
    estoque         INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_variacao_produto FOREIGN KEY (produto_id) REFERENCES produto (id) ON DELETE CASCADE
);

CREATE TABLE cupom (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(40) NOT NULL UNIQUE,
    tipo         VARCHAR(15) NOT NULL,
    valor        NUMERIC(10,2) NOT NULL,
    min_subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
    validade     DATE,
    ativo        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE carrinho (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT,
    session_id  VARCHAR(80),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_carrinho_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE TABLE item_carrinho (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrinho_id BIGINT NOT NULL,
    variacao_id BIGINT NOT NULL,
    quantidade  INTEGER NOT NULL,
    CONSTRAINT fk_item_carrinho_carrinho FOREIGN KEY (carrinho_id) REFERENCES carrinho (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_carrinho_variacao FOREIGN KEY (variacao_id) REFERENCES variacao_produto (id),
    CONSTRAINT uq_item_carrinho UNIQUE (carrinho_id, variacao_id)
);

CREATE TABLE pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          VARCHAR(40) NOT NULL UNIQUE,
    usuario_id      BIGINT,
    status          VARCHAR(25) NOT NULL,
    subtotal        NUMERIC(10,2) NOT NULL,
    frete           NUMERIC(10,2) NOT NULL DEFAULT 0,
    desconto        NUMERIC(10,2) NOT NULL DEFAULT 0,
    total           NUMERIC(10,2) NOT NULL,
    cupom_codigo    VARCHAR(40),
    end_cep         VARCHAR(9),
    end_logradouro  VARCHAR(160),
    end_numero      VARCHAR(20),
    end_complemento VARCHAR(80),
    end_bairro      VARCHAR(80),
    end_cidade      VARCHAR(80),
    end_uf          VARCHAR(2),
    rastreio        VARCHAR(60),
    gateway_id      VARCHAR(80),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

CREATE TABLE item_pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT NOT NULL,
    variacao_id    BIGINT,
    nome_produto   VARCHAR(180) NOT NULL,
    sku            VARCHAR(60),
    preco_unitario NUMERIC(10,2) NOT NULL,
    quantidade     INTEGER NOT NULL,
    subtotal       NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_item_pedido_pedido   FOREIGN KEY (pedido_id)   REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_pedido_variacao FOREIGN KEY (variacao_id) REFERENCES variacao_produto (id) ON DELETE SET NULL
);

CREATE INDEX idx_produto_categoria ON produto (categoria_id);
CREATE INDEX idx_variacao_produto  ON variacao_produto (produto_id);
CREATE INDEX idx_pedido_usuario    ON pedido (usuario_id);
CREATE INDEX idx_pedido_status     ON pedido (status);
